sdcard_image-rpi.bbclass: remove stamp file - it causes errors
ERROR: xfce4-base-image-1.0-r0 do_image_rpi_sdimg: Taskhash mismatch 78514159230b84384ef1943ba91355b8 versus b88ecd8d10ad89cab562aacd62fdfa17 for /home/superandy/data/oe-core/sources/meta-misc/recipes-image/xfce4/xfce4-base-image.bb.do_image_rpi_sdimg
ERROR: Taskhash mismatch 78514159230b84384ef1943ba91355b8 versus b88ecd8d10ad89cab562aacd62fdfa17 for /home/superandy/data/oe-core/sources/meta-misc/recipes-image/xfce4/xfce4-base-image.bb.do_image_rpi_sdimg

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>